### ISSUE TITLE
Error: Cannot find module '../lib/config'

### ISSUE THREAD

**Issue by vitorebatista** [TheOceanCleanup/Server#1]
When I execute `npm start` I have the error below.
Can anyone help me? Thanks

```
node ./bin/www

module.js:338
    throw err;
    ^
Error: Cannot find module '../lib/config'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\TFS\theoceancleanup\Server\middleware\authorisation.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\TFS\theoceancleanup\Server\npm-debug.log

```

**Comment by HPieters** [comment]
Hello @vitorebatista,

Ah yeah I guess this is something we didn't include in the README. You can easily create the file yourself and return a JSON with token. Config is only used here https://github.com/TheOceanCleanup/Server/blob/a83f06fcb2d3f5eedb77d87c9d1132bcca11c355/middleware/authorisation.js, and the token is secret for production. The project is currently not under active development, but we hope to continue some day.
